### ISSUE TITLE
php55u update resets fpm log folder owner/group

### ISSUE THREAD

**Issue by claude-ws01** [iuscommunity-pkg/php55u#16]
Hello,

For a long time I have been having issues with php-fpm's log file stopping being filled. Every time it is because the owner/group of the log folder has changed back to apache.

I use nginx and have unified most web server activities to a single user: nginx.

Long story short, this change of owner/group occurs when I do a yum update which includes, once a while, a php55u update.

2 points:
A. now that I'm writing about it, I realize that I could use different folder(s) name and that would most probably solve this issue.

B. on the other hand, by principle, I do not see what business has the update to change the ownership of the log folder. On an install, ok, but on an update, no.

More:

I did look around: users home group, php-fpm config, php config... and I have not found anything that relates to "apache" user. But I did find a lot inside the php55u.specs.
If you think I should open a ticket elsewhere, please advise me.

thx:)
Claude.

**Comment by carlgeorge** [comment]
Howdy @claude-ws01.  The behavior you are seeing is because the ownership of the log directory is set in the [spec file][1].

```
# log owned by apache for log
%attr(770,apache,apache) %dir %{_localstatedir}/log/php-fpm
```

The `%attr` macro does not give you the option to only set to ownership upon initial install and not upon updates.

This is something we inheirited from the [Fedora spec file][2] that we forked our package from.  It is set this way because the default configuration runs the fpm daemon [as the apache user][3].  It has been brought up [before][4] that this is not always preferable, especially in cases where httpd (apache) has never been installed on a system.  Fedora decided to address this by having httpd and nginx spec files create a `-filesystem` subpackage that creates directories and adds the relevant user, and having `php-fpm` require those.  Additionally, support for access control lists was added to PHP 5.6.5, so Fedora's default is to run the fpm daemon as apache, but [allow access to both the apache and nginx users][5].

In php56u, we decided to handle things differently.  The fpm daemon runs as the `php-fpm` user.  Using it in socket mode requires adding your webserver user to the `php-fpm` group.  It still defaults to listening on `127.0.0.1:9000`.


[1]: https://github.com/iuscommunity-pkg/php55u/blob/b9e916bfe0ce0c83ea46483999798d5ff0568000/SPECS/php55u.spec#L1740
[2]: http://pkgs.fedoraproject.org/cgit/php.git/tree/php.spec?h=f23&id=feba38555fc92c26c749409d51da2a34e3e63a13#n1424
[3]: https://github.com/iuscommunity-pkg/php55u/blob/b9e916bfe0ce0c83ea46483999798d5ff0568000/SOURCES/php-fpm-www.conf#L38-L41
[4]: https://bugs.launchpad.net/ius/+bug/1312972
[5]: http://pkgs.fedoraproject.org/cgit/php.git/tree/php-fpm-www.conf?h=f23&id=feba38555fc92c26c749409d51da2a34e3e63a13#n56

**Comment by carlgeorge** [comment]
This [mailing list post][1] is also relevant.

[1]: https://lists.launchpad.net/ius-community/msg01103.html

**Comment by claude-ws01** [comment]
Thank you for both, your elaborate answer, and the mailing list link.

a. I'm just a guy that is passing by, and simply raising a flag concerning a behavior that caused me some headaches, until I realized where the issue was occurring.

b. I read the post about having a php-fpm-nginx and defaults at installation time, which is another theme, and here's my grain of salt: I understand the php-fpm-nginx but find it a bit too much, just for handling a different user/group.  From my perspective, a default `php-fpm` user & group is fine, as I am used to set my own php's user & group (and php-fpm's configuration, and /var/www, and /var/log/, and...)

c. `Updating`, which is where I'm raising my flag. No matter how the web server is configured, when doing a software update it is common practice to respect and leave alone the current configuration in place. Resetting the ownership of folders to the default is not desirable (not to say, error inducing practice) and should not behave this way in the first place.

Do I make any sense?

thx:)
Claude.

**Comment by b-harper** [comment]
Hey @claude-ws01,

Thanks for the follow up.  I understand your line of thinking.  Unfortunately,  file permissions and ownership within a RPM work differently than a changes to configuration files.  I would say it is fairly rare to change permissions or ownership of files provided by a RPM.  

As you stated earlier, the solution to create a custom log location.  Updates won't overwrite the custom location within your configuration files and RPM won't try to 'correct' the file ownership or permissions of the default log location.

-Ben

**Comment by claude-ws01** [comment]
Hello Ben,

just for the sake of argumentation.

I think I understand quite well how essential it is for an RPM to check and correct file/folder permissions/ownership in order to insure proper functionality.

However, specifically in update context, the log folder ownership and location falls outside RPM's jurisdiction for the simple reason that it is part of the php-fpm's config files, as defined in:
- /etc/php-fpm.conf
`error_log = <myLogPath/file>`

- /etc/php-fpm/<myPool>.conf
`user = <myUser>`
`group = <myGroup>`


This is a question of coherence: why give the ability to set user/group daemon and log path/file, if the RPM update will reset the log folder ownership ?

You would say it is fairly rare to change ownership... I would say that frequency is simply irrelevant; the minute the user can diverge from the defaults (with a config parm) all subsequent update must/should respect the divergences from the defaults.

This respect for divergence in RPM updates brought me to trust them not to break anything.  99% of the time, I find RPM's to be very respectful of the 'ecosystem' it's updating.

Thx:)
Claude.

**Comment by b-harper** [comment]
Hey @claude-ws01,

You are preaching to the choir.  We totally agree with you.  Fedora and RHEL's historic approach (and IUS before php 5.6) of coupling Apache and PHP worked great when Apache was overwhelmingly popular.  Now that Apache has some competition,  that approach does not work well.  Both Fedora and IUS have taken steps to correct with issue in future versions, but it is far less straight forward update current versions.  If you have ideas we might have overlooked, we would love to hear them.

In regards to your general concerns about the updates not respecting all changes, that is bit tricky.   Fedora's packaging guidelines state that (stock) [log file locations should be own by the package][0].  Doing a quick search, I can not seem to find any requirements about ownership or permissions of the (stock) log file location.  There is some generally [information about permissions][1].  In general, I have observed that setting log file location ownership and permissions via %attr to match the default configuration is common.  We follow Fedora/RHEL way in doing things.  If this practice is something you are looking to change,  you would need to take it up with them.

-Ben
[0]: https://fedoraproject.org/wiki/Packaging:Guidelines#Log_Files
[1]: https://fedoraproject.org/wiki/Packaging:Guidelines#File_Permissions

**Comment by claude-ws01** [comment]
\*\* LOL\*\*  Thank you... I had a good humorous laugh.

I will proceed with a new log folder... wayayayayayay more direct :dart:

Kindly

Claude.

**Comment by b-harper** [comment]
Glad to hear you got a good laugh.  Let us know if you have any more questions or concerns.
